my_string=input('Как ваше здоровье?:')
print(len(my_string))
print('Как ваше здоровье?:'.upper())
print('Как ваше здоровье?:'.lower())
print('Как ваше здоровье?:'.replace(' ','#'))
print(my_string[0])
print(my_string[-1])
